name: cesiumrag
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - langchain
  - openai
  - chromadb
  - python-docx
  - pdf2image
  - pytesseract
  - pdfminer.six
  - markdown
  - tiktoken
  - faiss-cpu
  - transformers
  - sentence-transformers
  - tenacity
  - numpy
  - pandas
  - pyqt
  - markdown
  - pygments 
  - python-dotenv
  - python-markdown-math
  - pyqtwebengine
  - pip
  - langchain-openai
  - langchain-community
  - langchain-chroma
  - shutil
  - tqdm
  - pip:
    - unstructured
