name: cesiumrag
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
    - langchain
    - langchain-openai
    - langchain-community
    - chromadb
    - openai
    - unstructured
    - python-docx
    - pdf2image
    - pytesseract
    - pdfminer.six
    - markdown
    - tiktoken
    - faiss-cpu
    - transformers
    - sentence-transformers
    - tenacity
    - numpy
    - pandas
    - PyQt5
    - markdown
    - pygments 
    - python-dotenv